{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "application.fullname" . }}-pvc
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes}}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.reclaimPolicy }}
{{- end}}
